#!/bin/bash
#
# Script para correr trabajo serial
#

# Opciones SGE
#$ -l h_rt=01:59:00 # Setea 1 horas de wall clock time
#$ -V  # Exporta las variables de entorno
#$ -N T2_000  # El nombre del job
#$ -cwd # Cambia al directorio actual
##Seteo la cantidad de threads que se va a usar
#$ -v OMP_NUM_THREADS=2 ### Setea la cantidad de threads a 4


# Comando para correr el programa, tal cual lo llamaríamos desde la línea de comandos
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/lmoffatt.inquimae/local/gcc-6.2.0/lib64/

/home/lmoffatt.inquimae/Astro/release/Astro /home/lmoffatt.inquimae/Astro/Astro/run/evidence_script LABEL parameters_000
