#!/bin/bash

# Correr con `sbatch /ruta/a/este/script

#SBATCH --job-name="m_13"
#SBATCH --nodes=1                    # Use one node
#SBATCH --ntasks=1                   # Run a single task
#SBATCH --cpus-per-task=32            # Number of CPU cores per task
#SBATCH --workdir=/home/lmoffatt/Astro/astro/run/m13
#SBATCH --error="m13-%j.err"
#SBATCH --output="m13-%j.out"
#SBATCH --account=freeriders
#SBATCH --partition=freeriders
#SBATCH --time=01-23

echo "trabajo \"${SLURM_JOB_NAME}\""
echo "    id: ${SLURM_JOB_ID}"
echo "    partición: ${SLURM_JOB_PARTITION}"
echo "    nodos: ${SLURM_JOB_NODELIST}"
echo
date +"inicio %F - %T"

echo "
--------------------------------------------------------------------------------
"

# INICIO VARIABLES IMPORTANTES
#
# NO TOCAR. No se aceptan reclamos en caso de modificar estas líneas. Deberán
# incluirlas siempre, hasta próximo aviso.
#
[ -r /etc/profile.d/odin-users.sh ] && . /etc/profile.d/odin-users.sh
#
# FIN VARIABLES IMPORTANTES

# El path al programa es `/home/USUARIO/ejemplos/programa-openmp`. Como más
# arriba seteamos el directorio de trabajo a `/home/USUARIO/ejemplos`, el
# programa se encuentra en el directorio de trabajo, por lo que basta poner
# `./programa-openmp`.

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/lmoffatt/GCC-7.2.0/lib64/
export OMP_NUM_THREADS=32
srun /home/lmoffatt/Astro/parallel/Astro /home/lmoffatt/Astro/astro/run/evidence_script LABEL model_13


echo "
--------------------------------------------------------------------------------
"

date +"fin %F - %T"
