#!/bin/bash

# Correr con `sbatch /ruta/a/este/script

#SBATCH --job-name="om3_13"
#SBATCH --nodes=1                    # Use one node
##SBATCH --ntasks=1                   # Run a single task
##SBATCH --cpus-per-task=64            # Number of CPU cores per task
#SBATCH --workdir=/home/lmoffatt/Astro/astro/run/m13
#SBATCH --error="m13-%j.err"
#SBATCH --output="m13-%j.out"
#SBATCH --partition=free-rider
#SBATCH --mail-type=ALL
#SBATCH --mail-user=lmoffatt@gmail.com

echo "trabajo \"${SLURM_JOB_NAME}\""
echo "    id: ${SLURM_JOB_ID}"
echo "    partición: ${SLURM_JOB_PARTITION}"
echo "    nodos: ${SLURM_JOB_NODELIST}"
echo "    cpus per task: ${SLURM_CPUS_PER_TASK}"
echo
date +"inicio %F - %T"

echo "
--------------------------------------------------------------------------------
"


# El path al programa es `/home/USUARIO/ejemplos/programa-openmp`. Como más
# arriba seteamos el directorio de trabajo a `/home/USUARIO/ejemplos`, el
# programa se encuentra en el directorio de trabajo, por lo que basta poner
# `./programa-openmp`.

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/lmoffatt/GCC-7.2.0/lib64/

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
srun /home/lmoffatt/Astro/parallelOpt/Astro /home/lmoffatt/Astro/astro/run/evidence_script_tupac_3 LABEL model_13


echo "
--------------------------------------------------------------------------------
"

date +"fin %F - %T"
