#!/bin/bash

# Correr con `sbatch /ruta/a/este/script

#SBATCH --job-name="rs4_m101"
#SBATCH --nodes=1                    # Use one node
#SBATCH --ntasks=1                   # Run a single task
#SBATCH --cpus-per-task=8            # Number of CPU cores per task
#SBATCH --workdir=/home/lmoffatt/Astro/astro/run/m101
#SBATCH --error="rs4_m101-%j.err"
#SBATCH --output="rs4_m101-%j.out"
#SBATCH --account=freeriders
#SBATCH --partition=freeriders

echo "trabajo \"${SLURM_JOB_NAME}\""
echo "    id: ${SLURM_JOB_ID}"
echo "    partición: ${SLURM_JOB_PARTITION}"
echo "    nodos: ${SLURM_JOB_NODELIST}"
echo
date +"inicio %F - %T"

echo "
--------------------------------------------------------------------------------
"

# INICIO VARIABLES IMPORTANTES
#
# NO TOCAR. No se aceptan reclamos en caso de modificar estas líneas. Deberán
# incluirlas siempre, hasta próximo aviso.
#
[ -r /etc/profile.d/odin-users.sh ] && . /etc/profile.d/odin-users.sh
#
# FIN VARIABLES IMPORTANTES

# El path al programa es `/home/USUARIO/ejemplos/programa-openmp`. Como más
# arriba seteamos el directorio de trabajo a `/home/USUARIO/ejemplos`, el
# programa se encuentra en el directorio de trabajo, por lo que basta poner
# `./programa-openmp`.

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/lmoffatt/GCC-7.2.0/lib64/
export OMP_NUM_THREADS=8
srun /home/lmoffatt/Astro/parallel/Astro /home/lmoffatt/Astro/astro/run/Restart_script LABEL model_101 RESTART R_NM2_30_2k_E_250_50_model_101163635s136869_2329972451_state.txt

echo "
--------------------------------------------------------------------------------
"

date +"fin %F - %T"
