#!/bin/bash
#
# Script para correr trabajo serial
#

# Opciones SGE
#$ -l h_rt=23:59:00 # Setea 48 horas de wall clock time
##$ -l h_vmem=4G
##$ -l mem_free=4G
#$ -V  # Exporta las variables de entorno
#$ -N D01_2k30  # El nombre del job
#$ -cwd # Cambia al directorio actual



# Comando para correr el programa, tal cual lo llamaríamos desde la línea de comandos
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/lmoffatt.inquimae/local/gcc-6.2.0/lib64/

/home/lmoffatt.inquimae/Astro/release/Astro /home/lmoffatt.inquimae/Astro/Astro/run/evidence_script LABEL model_01
