#!/bin/bash

##cd /home/lmoffatt.inquimae/Astro/Astro/run/m01
##qsub p_m01



cd /home/lmoffatt.inquimae/Astro/Astro/run/m13
qsub rp1_m13

cd /home/lmoffatt.inquimae/Astro/Astro/run/m03
qsub rp1_m03

cd /home/lmoffatt.inquimae/Astro/Astro/run/m101
qsub rp1_m101
qsub rp2_m101



##cd /home/lmoffatt.inquimae/Astro/Astro/run/m02
##qsub p_m02

##cd /home/lmoffatt.inquimae/Astro/Astro/run/m10
##qsub p_m10

cd /home/lmoffatt.inquimae/Astro/Astro/run/m11
qsub rp1_m11

cd /home/lmoffatt.inquimae/Astro/Astro/run/m12
qsub rp1_m12
